# Generated by Django 6.0.2 on 2026-02-13 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('crops', 'Crops'), ('livestock', 'Livestock'), ('house_items', 'House_items')], default='crops', max_length=30)),
                ('name', models.CharField(max_length=20)),
                ('image', models.ImageField(null=True, upload_to='product/images')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('is_available', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
